services:
  redis:
    image: redis:alpine3.13
    ports:
      - 16379:6379
  postgresql:
    image: postgres:9.6.22
    ports:
      - 13306:3306
    volumes:
      - ./mount/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

